# fly.toml app configuration file generated for yichennew on 2023-09-11T00:16:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yichennew"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
